### ISSUE TITLE
Adding a separate page for sponsors and grants we have or will receive

### ISSUE THREAD

**Issue by pooyanjamshidi** [GamecockRobotics/GamecockRobotics.github.io#5]
Since we have received one grant, and we will probably receive more in the future, please add a new page listing the grants and info regarding them, as well as the sponsors, including the dollar amounts, or whatever they provide.

For now, please list this grant:
$5000, Community of Practice Grant, UofSC's Center for Integrative and Experiential Learning, 2021.

**Comment by NathanaelOliver** [comment]
Began work on this, designing a 2D packing algorithm in liquid to place sponsors and logos in a grid with varying sizes based on the tier of their contributions.

**Comment by pooyanjamshidi** [comment]
@NathanaelOliver I do not see the sponsors yet, please make sure you add the list of sponsors, especially the Community of Practice grant.

**Comment by Austin7856** [comment]
Added stars indicating which tier the sponsor falls under and added the sponsors page to the public website
